runtime: nodejs18
env: standard
# instance_class: F2

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 10m
# manual_scaling:
#   instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10